<?php

use yii\db\Migration;

/**
 * Class m210720_023954_add_pudong_swim_address
 */
class m210720_023954_add_pudong_swim_address extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $sql = <<<EOF
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (1, '南汇游泳馆', '', '上海市', '上海市', '浦东新区', '浦东新区浦东新区观海路1000号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (2, '浦东游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东南路3699号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (4, '仁恒河滨城', NULL, '上海市', '上海市', '浦东新区', '浦东新区丁香路1399弄18号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (5, '四季雅苑会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区花木路1983弄288号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (7, '上海淳大万丽酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区迎春路719号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (9, '由由喜来登', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦建路38号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (10, '上海世纪皇冠假日酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东新区民生路1433号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (13, '张江高科技园区健身中心', NULL, '上海市', '上海市', '浦东新区', '浦东新区哈雷路899号4幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (18, '绿宝俱乐部', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东沪南路2888号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (19, '红塔豪华精选酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区东方路889号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (20, '绿宇酒店游泳池', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦和路99弄90号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (21, '金谊河畔会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区上南路永泰路595弄69号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (22, '金桥美格菲运动俱乐部', NULL, '上海市', '上海市', '浦东新区', '浦东新区蓝天路600号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (27, '金桥文体中心', NULL, '上海市', '上海市', '浦东新区', '浦东新区金高路1777号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (30, '星之健身游泳馆（张江店）', NULL, '上海市', '上海市', '浦东新区', '浦东新区科苑路88号德国中心公寓楼B1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (31, '新城万嘉碧翠园', NULL, '上海市', '上海市', '浦东新区', '浦东新区繁锦路1288弄51号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (33, '福奥健身康桥分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区康桥路1388弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (35, '紫金山大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区东方路778号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:43');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (36, '丽思卡尔顿酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区世纪大道8号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (37, '一兆韦德阳光店', NULL, '上海市', '上海市', '浦东新区', '浦东新区佳林路53号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (38, '一兆韦德张江店', NULL, '上海市', '上海市', '浦东新区', '浦东新区春晓路81号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (39, '一兆韦德张杨店', NULL, '上海市', '上海市', '浦东新区', '浦东新区桃林路777号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (40, '金仕堡张江会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区晨晖路728号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (41, '迈博游泳馆花木店', NULL, '上海市', '上海市', '浦东新区', '浦东新区银霄路243号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (43, '一兆韦德大华锦绣会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东成山路1879号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (44, '一兆韦德菊园店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦城路367号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (45, '上海外高桥皇冠假日酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区杨高北路1000号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (48, '仁恒滨江园', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路99弄22号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (49, '威尔士世纪公园店', NULL, '上海市', '上海市', '浦东新区', '浦东新区花木路银霄路5号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (51, '金地旭海会', NULL, '上海市', '上海市', '浦东新区', '浦东新区航鹤路1135号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (52, '威尔士航头店', NULL, '上海市', '上海市', '浦东新区', '浦东新区航鹤路78弄1406号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (53, '动感健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区靖海南路565号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (54, '金仕堡张杨北路店', NULL, '上海市', '上海市', '浦东新区', '浦东新区张杨北路1151号1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (57, '威尔士世纪海景店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路1288弄7号地下1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (58, '威尔士祖冲之路', NULL, '上海市', '上海市', '浦东新区', '浦东新区祖冲之路1239弄7号地下一层01室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (62, '仁恒滨江园（一期、二期室外池）', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路99弄22号、23号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (63, '仁恒滨江园（三期室外池）', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路99弄22号、23号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (64, '仁恒河滨城室外池', NULL, '上海市', '上海市', '浦东新区', '浦东新区丁香路1399弄18号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (65, '怡健身平度店', NULL, '上海市', '上海市', '浦东新区', '浦东新区平度路258号6号楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (67, '红波浪游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦东新区新场镇沪南公路7178号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:44');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (68, '一兆韦德浦东六分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区成山路1879号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (69, '喜马拉雅酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区梅花路1108号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (71, '凯宾斯基大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东新区陆家嘴环路1288号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (72, '两河流域健身会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区航鹤路1699弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (73, '浦东假日酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区东方路899号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (74, '云间四季酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦绣东路418弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (75, '美国环球健身星河湾店', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦绣路2486号3号地下室1层A区', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (77, '滨江凯旋门', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路688弄18、49号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (78, '威尔士周浦印象生活广场', NULL, '上海市', '上海市', '浦东新区', '浦东新区年家浜东路159弄88号地上一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (79, '上海阿瑞拉斯健身管理有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区新金桥路1599号17幢E2a', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (80, '大华假日酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦尊路399号三层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (81, '上海天亚健身管理有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区秀浦路886号内第一层（1-2）', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (83, '上海顶尚健身休闲有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区红枫路288号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (85, '一兆韦德浦东十五分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区大同路53号8号楼101、201、301室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (86, '金桥百姓游泳池', NULL, '上海市', '上海市', '浦东新区', '浦东新区乐园路8号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (87, '曹路体育中心游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东金群路58号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (88, '金桥红枫万豪', NULL, '上海市', '上海市', '浦东新区', '浦东新区新金桥路15号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (89, '美再晨运动', NULL, '上海市', '上海市', '浦东新区', '浦东新区松涛路251号-1', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (90, '美格菲金桥店', NULL, '上海市', '上海市', '浦东新区', '浦东新区川桥路599号3、4层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (91, '美再晨健身(九城店)', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦绣路300弄35号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:45');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (93, '兴荣豪廷大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东大道2288号（近德平路）', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (94, '美再晨健身游泳锦绣店', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦安东路88弄6号（锦绣满堂花园小区内）', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (96, '慕蔺酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路266号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (97, '上海金游健康信息咨询有限公司分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区严家桥1号8号楼102室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (98, '东锦江大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区杨高南路889号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (99, '通茂大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区松林路357号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (101, '浦东星河湾酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦绣路2588号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (103, '金桥华美达', NULL, '上海市', '上海市', '浦东新区', '浦东新区新金桥路18号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (105, '康斐斯健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区沈梅路123弄1-3号A区', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (106, '威尔士成山路店', NULL, '上海市', '上海市', '浦东新区', '浦东新区成山路2388弄1号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (107, '威尔士樱花路店', NULL, '上海市', '上海市', '浦东新区', '浦东新区樱花路80弄2号三层301室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (109, 'IFIT天行健', NULL, '上海市', '上海市', '浦东新区', '浦东新区洲海路999号B栋201室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (110, '亲和源度假酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区秀沿路3101号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (111, '凯德莲公馆会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区齐恒路33弄9号D栋负一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (112, '青柠健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区牌楼东路528弄182号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (113, '鸿艺会', NULL, '上海市', '上海市', '浦东新区', '浦东新区红枫路588号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (114, '星之健东方路', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦电路400号三楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (115, '美再晨运动天之骄子店', NULL, '上海市', '上海市', '浦东新区', '浦东新区盛夏路58弄25/26号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (117, '一兆韦德周浦绿地缤纷城', NULL, '上海市', '上海市', '浦东新区', '浦东新区年家浜东路238号4层401', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:46');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (120, '浦东绿地假日酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东新区秀沿路1088号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (121, '下沙百姓', NULL, '上海市', '上海市', '浦东新区', '浦东新区下沙新街188号6幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (122, '金领会健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区川沙路1215号10幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (123, '上海海锦体育发展有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区申江路7171弄1号101室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (124, '仁恒雅苑运动中心', NULL, '上海市', '上海市', '浦东新区', '浦东新区兰谷路2199弄2111号B1层A区', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (125, '超想健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区钦公唐路501号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (126, '上海维达体育管理有限公司金桥分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区黄杨路65弄1号3层会所', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (128, '金仕堡健身杨思店', NULL, '上海市', '上海市', '浦东新区', '浦东新区长清路507号1幢地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (129, '美再晨运动会馆塘桥店', NULL, '上海市', '上海市', '浦东新区', '浦东新区临沂北路150弄2号楼2楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (130, '上海创体健身管理有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区云台路800号3层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (131, '诺富特酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区秀浦路3188弄1号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (132, '上海旭恒商业经营管理有限公司唐镇路分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区唐镇路138弄93号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (133, '宝龙丽笙酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区金海路2449弄2号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (134, '花木绿城兰亭', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦建路1399弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (135, '仁恒森兰雅苑一期', NULL, '上海市', '上海市', '浦东新区', '浦东新区兰谷路1888弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (136, '仁恒森兰雅苑二期', NULL, '上海市', '上海市', '浦东新区', '浦东新区兰谷路2188弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (137, '绿城御园', NULL, '上海市', '上海市', '浦东新区', '浦东新区兰谷路2777弄50号地下一', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (138, '中油大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区东方路969号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (139, '鸿艺会室外池', NULL, '上海市', '上海市', '浦东新区', '浦东新区红枫路588号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (140, '上海旭恒商业经营管理有限公司宏雅路分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区宏雅路150弄26号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:47');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (141, '金茂君悦大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦东世纪大道88号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (142, '上海睦爱健身管理有限公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区苗圃路218弄28号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (143, '香格里拉大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区富城路33号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (144, '超想健身惠南店', NULL, '上海市', '上海市', '浦东新区', '浦东新区沪南公路9936弄58号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (145, '一兆韦德健身管理有限公司十八分公司', NULL, '上海市', '上海市', '浦东新区', '浦东新区沪南公路5588-5592号1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (146, '上海建桥学院', NULL, '上海市', '上海市', '浦东新区', '浦东新区沪城环路1111号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (147, '中邦颐道酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区王桥路999号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (148, '康桥万豪酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区康新公路4499号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (149, '皇廷花园酒店', NULL, '上海市', '上海市', '浦东新区', '浦东新区华夏东路1539号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (150, '外高桥喜来登', NULL, '上海市', '上海市', '浦东新区', '浦东新区基隆路28号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (151, '威尔士张江店', NULL, '上海市', '上海市', '浦东新区', '浦东新区祖冲之路2288弄3号114室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (152, '威尔士张杨路店', NULL, '上海市', '上海市', '浦东新区', '浦东新区崮山路538号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (153, '广兰丽园室外池', NULL, '上海市', '上海市', '浦东新区', '浦东新区青桐路409弄16号一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (154, '仁恒森兰雅苑三期室外池', NULL, '上海市', '上海市', '浦东新区', '浦东新区兰谷路1777弄10号103物业用房', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (155, '瑨健身会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区百业路167弄11号4楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (156, '仁恒东邑雅苑', NULL, '上海市', '上海市', '浦东新区', '浦东新区玉盘北路288弄61号109、110室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (157, '九龙仓滨江健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区浦明路1199弄10号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (158, '贵龙园', NULL, '上海市', '上海市', '浦东新区', '浦东新区东方路1663弄1号A6室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (159, '贝菲特健身', NULL, '上海市', '上海市', '浦东新区', '浦东新区梅花路1-9号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (160, '首善财富俱乐部', NULL, '上海市', '上海市', '浦东新区', '浦东新区花木路1883弄96-98号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:48');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (161, '迪士尼乐园酒店', NULL, '上海市', '上海市', '浦东新区', '申迪西路1009号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (162, '纽斯浴场游泳池', NULL, '上海市', '上海市', '浦东新区', '东绣路288号、300号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (163, '新健身北蔡店', NULL, '上海市', '上海市', '浦东新区', '五星路706弄1号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (164, '海神诺富特大酒店', NULL, '上海市', '上海市', '浦东新区', '浦东大道728号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (165, '仁恒世纪公寓游泳馆', NULL, '上海市', '上海市', '浦东新区', '银融路88弄10号103、11号103、15号1层、16号1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (166, 'Evolution Sports', NULL, '上海市', '上海市', '浦东新区', '云山路1988号地下一层105C室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (167, '胜帝健身游泳馆', NULL, '上海市', '上海市', '浦东新区', '金高路435号2层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (168, '张江游泳馆', NULL, '上海市', '上海市', '浦东新区', '青桐路19弄1号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (169, '东方体育中心', NULL, '上海市', '上海市', '浦东新区', '耀体路701号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (170, '恩然酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '周邓公路5333弄1号401室、2号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (171, '绿城会所室外池', NULL, '上海市', '上海市', '浦东新区', '锦和路99弄90号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (172, '博雅酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '碧波路699号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (173, '证大美爵酒店游泳池', NULL, '上海市', '上海市', '浦东新区', '迎春路1199号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (174, '三甲港铂瑞酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '华夏东路6666弄3号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (175, '一兆韦德祝桥店游泳馆', NULL, '上海市', '上海市', '浦东新区', '航亭环路399弄87-88号1层、地下1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (176, '鲁能金威万豪侯爵酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦明路988号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (177, '澳丽花园游泳馆', NULL, '上海市', '上海市', '浦东新区', '浦建路60弄18号1-2层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (178, '航头体育中心游泳馆', NULL, '上海市', '上海市', '浦东新区', '航鹤路388号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (179, '热带风情会所室内池', NULL, '上海市', '上海市', '浦东新区', '潍坊西路1弄16号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (180, '热带风情会所室外池', NULL, '上海市', '上海市', '浦东新区', '潍坊西路1弄16号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:49');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (181, '动感天地会所', NULL, '上海市', '上海市', '浦东新区', '潍坊西路2弄20号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (182, '一兆韦德三林店', NULL, '上海市', '上海市', '浦东新区', '高青路2878弄1号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (183, '尚海郦景游泳馆', NULL, '上海市', '上海市', '浦东新区', '桃林路299弄47、57号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (184, '万科五玠坊游泳馆', NULL, '上海市', '上海市', '浦东新区', '东明路2100号S101、S102、SN101', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (185, '沃威尔国际健身', NULL, '上海市', '上海市', '浦东新区', '行南路349弄55号4幢A5-A6部位', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (186, '亚历山大金桥店游泳馆', NULL, '上海市', '上海市', '浦东新区', '枣庄路477号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (187, '梧桐人家会所游泳馆', NULL, '上海市', '上海市', '浦东新区', '忘忧路100弄2、3、12、13号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (188, '正地科雅大酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '张杨北路5658号四层401室、五层501室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (189, '一兆韦德周浦万达店', NULL, '上海市', '上海市', '浦东新区', '年家浜路538号B座4楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (191, '天赐泉浴室上南店', NULL, '上海市', '上海市', '浦东新区', '上南路6695、6697号一幢一层110室、二层206-212室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (192, '舒适堡张江店', NULL, '上海市', '上海市', '浦东新区', '海趣路162号301单元、4＿4夹层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (193, '怡健身游泳馆', NULL, '上海市', '上海市', '浦东新区', '溪兰路289弄2号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (194, '一兆韦德五莲路店', NULL, '上海市', '上海市', '浦东新区', '五莲路1769弄46号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (196, '嘉里大酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '花木路1388号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (197, '一兆韦德崂山店', NULL, '上海市', '上海市', '浦东新区', '崂山东路401号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (198, '健康城市健身俱乐部', NULL, '上海市', '上海市', '浦东新区', '方竹路185号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (200, '美国环球健身三林店', NULL, '上海市', '上海市', '浦东新区', '永泰路1155号第三层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (201, '美格菲三林店', NULL, '上海市', '上海市', '浦东新区', '林展路298号地下一层22-1室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (202, '锦江汤臣洲际大酒店', NULL, '上海市', '上海市', '浦东新区', '张杨路777号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (203, '威尔士滨江大道店', NULL, '上海市', '上海市', '浦东新区', '滨江大道1773弄11幢16号地下1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (204, '威尔士东郊百联店', NULL, '上海市', '上海市', '浦东新区', '沪南路2420号8幢第2F层G50-F02-1-025室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:50');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (205, '上科大游泳馆', NULL, '上海市', '上海市', '浦东新区', '海科路550号101室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (206, '极乐川沙温泉馆', NULL, '上海市', '上海市', '浦东新区', '川周路7076弄2号2幢、3幢、5幢、6幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (207, '一兆韦德曹路店', NULL, '上海市', '上海市', '浦东新区', '金钻路828弄9号地下一层105室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (208, '一兆韦德永乐店', NULL, '上海市', '上海市', '浦东新区', '上南路6717、梓康路561号5A1室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (209, '柏悦酒店水境水疗中心', NULL, '上海市', '上海市', '浦东新区', '自由贸易试验区世纪大道100号地下2楼东首、1楼东首、79-88楼、90-93楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (210, '一兆韦德阳光城店', NULL, '上海市', '上海市', '浦东新区', '高科东路777弄9号101室-107室、201室-206室、301-311室，10号215室-222室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (211, '金吉鸟陈春路店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区陈春路299号二层北区', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (212, '沃威尔康桥店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区康沈路219-231（单）号3层301室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (213, '四季华发康体中心', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区茂春路23号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (214, '一兆韦德御桥活力城店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区沪南路2229号商业裙房L5020室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (215, '仁恒世纪公寓室外池', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区银融路88弄10号103、11号103、15号1层、16号1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (216, '浩恒健身梧桐苑店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区康沈路2028号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (217, '沃威尔健身惠南店', NULL, '上海市', '上海市', '浦东新区', '浦东新区惠南镇拱泰路63、69号3层、4层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (218, '绿城玉兰花园', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区齐爱路99弄31-33号地下-1层、1层、1夹层会所', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (219, '一兆韦德中央公寓店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区东绣路99弄32号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (220, '海富花园游泳池', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区东方路1369号底层4', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (221, '大名城紫金九号会所', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区德淳路99弄12号101室、102室、103室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (222, '金磐会游泳池', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区东泰路200弄3号会所', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (223, '东江苑运动城', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区凯庆路299号1-3、5-11层，仁庆路388号106、201、302室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:51');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (224, '提香别墅会所', NULL, '上海市', '上海市', '浦东新区', '浦东新区康桥镇秀沿路1弄188号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (225, '一兆韦德苗圃店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区浦东大道1824号一层-5及地下一层-5', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (226, '迈博健身博山路店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区博山路199弄4号地下一层会所', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (227, '活力滨江游泳馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区启帆路517号B1层B103-1号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (228, '大团百姓游泳池', NULL, '上海市', '上海市', '浦东新区', '浦东新区大团镇南芦公路888号3幢一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (229, '万科蓝山会', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区金海路3333弄566、567号一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (230, '威尔士大华斐勒公园店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区华鹏路117号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (231, '东源丽晶别墅会所', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区巨峰路1589弄185号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (232, '东方文华酒店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区浦东南路111、139号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (233, '源深体育中心游泳馆', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区张杨路1458号东侧', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (234, '浩恒健身医学园店', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区周祝公路268弄1号336、337、338、339、350、351、352、353、355、356、357、401室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (235, 'HBBC健身', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区御桥路270弄34-35号1-2层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (236, '世博洲际酒店游泳馆', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区雪野路1188号', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (237, '海之宝游泳俱乐部', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区耀江路590号1号楼、2号楼、3号楼', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (238, '绿城玉兰花园臻园', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区齐爱路168弄177号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (239, '炼猫游泳馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区三灶浜路150号1幢、2幢、4幢1层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (240, '艺渊游泳', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区惠南镇文益街99弄7号2层，9、11号2层，13号2层，15号2层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (241, '欧帝温水游泳馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区城南路200号5幢、6幢、7幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (242, '三林体育中心游泳馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区云莲路201号1幢北区1-2层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:52');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (243, '群胜健身游泳运动中心', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区上川路1539号2幢', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (244, '云间绿大地会所室外池', NULL, '上海市', '上海市', '浦东新区', '浦东新区锦绣东路418弄', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (245, '一兆韦德塘桥店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区浦建路15号地下一层1-13室、42-49室、58-65室、70-118室、121-123室、127-129室、175-186室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (246, '嗨达健身', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区东明路355弄1-3号一至三层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (247, '格致游泳馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区博兴路760弄31号一层及地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (248, '绿城玉兰公馆', NULL, '上海市', '上海市', '浦东新区', '上海市浦东新区春源路58弄6-7号地下一层', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
INSERT INTO `pudongswim`.`swim_address` (`id`, `name`, `imgurl`, `province`, `city`, `district`, `address`, `longitude`, `latitude`, `lane`, `comment_num`, `comment_sum_score`, `publish`, `status`, `create_time`, `update_time`) VALUES (249, '美再晨东方店', NULL, '上海市', '上海市', '浦东新区', '中国（上海）自由贸易试验区上海市浦东新区东方路1688号101、102-A、201、203、204、205、206、302室', NULL, NULL, NULL, 0, 0, 1, 1, NULL, '2021-07-20 10:40:53');
EOF;

        $this->execute($sql);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210720_023954_add_pudong_swim_address cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210720_023954_add_pudong_swim_address cannot be reverted.\n";

        return false;
    }
    */
}
